import type { PublicationPaper } from '../types/publication';

export const demoPublicationPapers: PublicationPaper[] = [
  {
    id: 'demo-published-urban-heat',
    title: 'Street-Level Tree Canopy and Urban Heat Exposure in Ho Chi Minh City',
    abstract: 'This study combines street imagery, temperature observations, and neighborhood indicators to examine how tree canopy distribution relates to daytime heat exposure across urban districts.',
    authors: [
      { id: 'a-1', name: 'Nguyen Minh Anh', institutionIds: ['i-1'], orcid: '0000-0002-1825-0097', order: 1 },
      { id: 'a-2', name: 'Tran Gia Han', institutionIds: ['i-2'], order: 2 },
    ],
    institutions: [
      { id: 'i-1', name: 'Vietnam National University Ho Chi Minh City' },
      { id: 'i-2', name: 'University of Economics Ho Chi Minh City' },
    ],
    doi: '10.5555/ars.demo.2026.001',
    publicationDate: '2026-08-04',
    paperType: 'Research article',
    domain: 'Environmental science',
    field: 'Urban climate',
    subfield: 'Heat resilience',
    topics: ['Urban heat', 'Tree canopy', 'Climate adaptation'],
    keywords: ['remote sensing', 'public health', 'cities'],
    version: 2,
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    createdAt: '2026-06-04T08:00:00.000Z',
    submittedAt: '2026-06-06T08:00:00.000Z',
    publishedAt: '2026-08-04T08:00:00.000Z',
    reviewer: {
      reviewerName: 'Dr. Le Quang Huy',
      recommendation: 'ACCEPT',
      privateComments: 'Private editorial review content is intentionally excluded from the catalog.',
      privateScores: { originality: 5, methodology: 4 },
      submittedAt: '2026-07-22T08:00:00.000Z',
    },
    reviewerIdentityPublic: true,
    researcherVerificationStatus: 'VERIFIED',
  },
  {
    id: 'demo-published-learning-analytics',
    title: 'Transparent Learning Analytics for Research Writing Feedback',
    abstract: 'A mixed-methods evaluation of transparent feedback signals for postgraduate research-writing workshops, focused on feedback timing, student agency, and revision quality.',
    authors: [
      { id: 'a-3', name: 'Pham Thu Bao', institutionIds: ['i-3'], order: 1 },
    ],
    institutions: [
      { id: 'i-3', name: 'Can Tho University' },
    ],
    openAlexId: 'W999999001',
    externalIdentifier: 'arXiv:2608.01001',
    publicationDate: '2026-08-18',
    paperType: 'Methodology article',
    domain: 'Education',
    field: 'Learning analytics',
    subfield: 'Academic writing',
    topics: ['Feedback', 'Research writing', 'Learning analytics'],
    keywords: ['higher education', 'revision', 'transparency'],
    version: 1,
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    createdAt: '2026-07-03T08:00:00.000Z',
    publishedAt: '2026-08-18T08:00:00.000Z',
    reviewerIdentityPublic: false,
    researcherVerificationStatus: 'VERIFIED',
  },
  {
    id: 'demo-private-draft',
    title: 'Private Draft That Must Never Reach the Catalog',
    abstract: 'This fixture proves catalog filtering in tests and demos.',
    authors: [{ id: 'a-4', name: 'Internal Author', institutionIds: ['i-4'], order: 1 }],
    institutions: [{ id: 'i-4', name: 'Internal Institution' }],
    paperType: 'Research article',
    topics: ['Internal'],
    keywords: ['draft'],
    version: 1,
    status: 'DRAFT',
    visibility: 'PRIVATE',
    createdAt: '2026-08-20T08:00:00.000Z',
    reviewerIdentityPublic: false,
    researcherVerificationStatus: 'PENDING',
  },
  {
    id: 'demo-under-review',
    title: 'Under Review Paper That Must Never Reach the Catalog',
    abstract: 'This fixture proves public privacy filtering.',
    authors: [{ id: 'a-5', name: 'Private Researcher', institutionIds: ['i-5'], order: 1 }],
    institutions: [{ id: 'i-5', name: 'Private Institution' }],
    paperType: 'Research article',
    topics: ['Internal'],
    keywords: ['review'],
    version: 1,
    status: 'UNDER_REVIEW',
    visibility: 'PRIVATE',
    createdAt: '2026-08-16T08:00:00.000Z',
    reviewerIdentityPublic: false,
    researcherVerificationStatus: 'VERIFIED',
    reviewer: {
      reviewerName: 'Private Reviewer',
      recommendation: 'REVISION_REQUIRED',
      privateComments: 'This must remain private.',
      privateScores: { methodology: 2 },
    },
  },
];
